# Generated by Django 3.0.3 on 2020-04-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.AddField(
            model_name='marker',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voyages.Position'),
        ),
        migrations.AddField(
            model_name='marker',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.Voyage'),
        ),
    ]
