# Generated by Django 3.0.3 on 2020-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_auto_20200425_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='position',
        ),
        migrations.AddField(
            model_name='marker',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
