# Generated by Django 3.0.3 on 2020-04-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_auto_20200425_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat1', models.FloatField()),
                ('lng1', models.FloatField()),
                ('lat2', models.FloatField()),
                ('lng2', models.FloatField()),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.Voyage')),
            ],
        ),
    ]
